# Generated by Django 3.2.6 on 2023-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'search results',
            },
        ),
    ]
