# Generated by Django 3.2.6 on 2023-07-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsarticle',
            table=None,
        ),
    ]
